#SPDX-License-Identifier: MIT-0
---
api_port: 6443  # noqa var-naming[no-role-prefix]
server_group: k3s_cluster  # noqa var-naming[no-role-prefix]
agent_group: load_generator  # noqa var-naming[no-role-prefix]
# defaults file for roles/prereq
