#SPDX-License-Identifier: MIT-0
---
- name: Add Helm repository for Jaeger
  kubernetes.core.helm_repository:
    name: jaegertracing
    repo_url: "https://jaegertracing.github.io/helm-charts"

- name: Install Jaeger (All-in-One, In-Memory)
  kubernetes.core.helm:
    name: jaeger
    chart_ref: jaegertracing/jaeger
    release_namespace: observability
    create_namespace: true
    state: "{{ stack_state | default('present') }}"
    wait: true
    values:
      provisionDataStore: shared
      allInOne:
        enabled: true
      storage:
        type: memory
        options:
          memory:
            max-traces: 100000
      agent:
        enabled: false
      collector:
        enabled: false
      query:
        enabled: false

- name: Create dedicated NodePort Service for Jaeger UI
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: jaeger-ui-nodeport
        namespace: observability
      spec:
        type: NodePort
        selector:
          app.kubernetes.io/name: jaeger #Connect to main pod
        ports:
          - name: ui
            port: 16686
            targetPort: 16686
            nodePort: 30086
