#!/usr/bin/env python3
"""
plot_metrics.py – Offline Prometheus metric visualisation (dynamic)
===================================================================
Reads directly from the raw_data_<stack>.csv file generated by dump_prometheus_data.py.
Computes mean ± std across iterations, and plots error-band charts.

Dynamically discovers ALL metrics present in the CSV.
Network/Disk byte-rate metrics are automatically converted to MB/s.

Usage:
    python3 plot_metrics.py <stack_name>
"""

import argparse
import math
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ─── Unit conversion & label rules ───────────────────────────────────────
UNIT_RULES = [
    # Pattern substring    Y-axis label          Divisor (raw value → display)
    ("CPU",               "CPU (cores)",          1),
    ("RAM",               "RAM (MiB)",            1024 ** 2),
    ("NetRX",             "Network RX (MB/s)",    1e6),
    ("NetTX",             "Network TX (MB/s)",    1e6),
    ("DiskWrite",         "Disk Write (MB/s)",    1e6),
    ("Logs_Ingestion",    "Log Ingest (MB/s)",    1e6),
    ("Spans_Ingestion",   "Spans/s",              1),
    ("Context_Switches",  "Switches/sec",         1),
]

DEFAULT_YLABEL = "Value"
DEFAULT_DIVISOR = 1


def resolve_units(metric_name: str) -> tuple[str, float]:
    for pattern, ylabel, divisor in UNIT_RULES:
        if pattern in metric_name:
            return ylabel, divisor
    return DEFAULT_YLABEL, DEFAULT_DIVISOR


def pretty_title(metric_name: str) -> str:
    parts = metric_name.replace("_", " – ", 1).replace("_", " ")
    return parts


def align_and_resample(series_list: list[pd.DataFrame], freq_seconds: float = 5.0):
    if not series_list:
        return np.array([]), np.array([])

    max_duration = max(df["time_relative"].max() for df in series_list if not df.empty)
    if pd.isna(max_duration):
        return np.array([]), np.array([])

    grid = np.arange(0, max_duration + freq_seconds, freq_seconds)
    resampled = []

    for df in series_list:
        if df.empty:
            resampled.append(np.full_like(grid, np.nan))
            continue
        interp = np.interp(grid, df["time_relative"].values, df["value"].values,
                           left=np.nan, right=np.nan)
        resampled.append(interp)

    return grid, np.array(resampled)


def main():
    parser = argparse.ArgumentParser(description="Plot metrics from raw CSV data.")
    parser.add_argument("stack_name", help="Stack name (e.g., stack_0)")
    args = parser.parse_args()

    results_dir = os.path.join(os.path.dirname(__file__), "results")
    csv_path = os.path.join(results_dir, f"raw_data_{args.stack_name}.csv")

    if not os.path.isfile(csv_path):
        print(f"ERROR: Raw data file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading offline data from {csv_path}...")
    df = pd.read_csv(csv_path)

    test_ids = sorted(df["test_name"].unique())
    all_metrics = sorted(df["metric_name"].unique())
    print(f"Tests found in CSV:   {test_ids}")
    print(f"Metrics found in CSV: {all_metrics}\n")

    for test_id in test_ids:
        test_df = df[df["test_name"] == test_id]
        iterations = sorted(test_df["iteration"].unique())
        n_iter = len(iterations)

        available_metrics = sorted(test_df["metric_name"].unique())
        n_metrics = len(available_metrics)

        if n_metrics == 0:
            print(f"  WARN: No metrics for {test_id}, skipping.")
            continue

        ncols = 2 if n_metrics > 1 else 1
        nrows = math.ceil(n_metrics / ncols)

        fig, axes = plt.subplots(nrows, ncols, figsize=(8 * ncols, 5 * nrows), squeeze=False)
        fig.suptitle(
            f"{args.stack_name.upper()} – {test_id.upper()}  ({n_iter} iter, mean ± σ)",
            fontsize=15,
            fontweight="bold",
        )

        for idx, metric_name in enumerate(available_metrics):
            row, col = divmod(idx, ncols)
            ax = axes[row][col]
            ylabel, divisor = resolve_units(metric_name)

            metric_df = test_df[test_df["metric_name"] == metric_name]

            iter_frames = []
            for it in iterations:
                it_df = metric_df[metric_df["iteration"] == it].sort_values("time_relative")
                if not it_df.empty:
                    iter_frames.append(it_df)

            if not iter_frames:
                ax.set_title(f"{pretty_title(metric_name)}\n(no data)")
                continue

            time_axis, values_2d = align_and_resample(iter_frames)
            if len(time_axis) == 0:
                ax.set_title(f"{pretty_title(metric_name)}\n(no data)")
                continue

            mean = np.nanmean(values_2d, axis=0) / divisor
            std = np.nanstd(values_2d, axis=0) / divisor

            t_min = time_axis / 60.0

            ax.plot(t_min, mean, linewidth=2, label="mean")
            if n_iter > 1:
                ax.fill_between(t_min, mean - std, mean + std, alpha=0.25, label="± 1 σ")

            ax.set_ylabel(ylabel)
            ax.set_xlabel("Time (min)")
            ax.set_title(pretty_title(metric_name))
            ax.legend(loc="upper right", fontsize=9)
            ax.grid(True, linestyle="--", alpha=0.5)
            ax.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))

        for idx in range(n_metrics, nrows * ncols):
            row, col = divmod(idx, ncols)
            axes[row][col].set_visible(False)

        plt.tight_layout()
        out_path = os.path.join(results_dir, f"{args.stack_name}_{test_id}_dashboard.png")
        plt.savefig(out_path, dpi=200, bbox_inches="tight")
        plt.close(fig)
        print(f"    → saved: {out_path}")

    print("\nDone. All plots generated from CSV!")

if __name__ == "__main__":
    main()
