#!/usr/bin/env python3
"""
plot_metrics.py – Prometheus-based metric extraction & visualisation
====================================================================
Reads test timestamps from the CSV generated by run_all_tests.sh,
queries Prometheus HTTP API for each (test, iteration) window,
computes mean ± std across iterations, and plots error-band charts.

Usage:
    python3 plot_metrics.py <stack_name> [--prometheus URL]

Example:
    python3 plot_metrics.py stack1_otel
    python3 plot_metrics.py baseline --prometheus http://10.0.0.5:30090
"""

import argparse
import sys
import os
from collections import defaultdict

import numpy as np
import pandas as pd
import requests
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# ── Prometheus queries ──────────────────────────────────────────────────────
QUERIES = {
    "CPU – Application (default)": (
        'sum(rate(container_cpu_usage_seconds_total{namespace="default"}[1m]))',
        "CPU (cores)",
    ),
    "CPU – Observability agents": (
        'sum(rate(container_cpu_usage_seconds_total{namespace=~"observability|logging|monitoring|istio-system|kube-system", container!=""}[1m]))',
        "CPU (cores)",
    ),
    "RAM – Application (default)": (
        'sum(container_memory_working_set_bytes{namespace="default"})',
        "RAM (bytes)",
    ),
    "RAM – Observability agents": (
        'sum(container_memory_working_set_bytes{namespace=~"observability|logging|monitoring|istio-system|kube-system"})',
        "RAM (bytes)",
    ),
}

STEP = "5s"  # query resolution

# ── Helpers ─────────────────────────────────────────────────────────────────

def query_prometheus(prom_url: str, promql: str, start: int, end: int) -> pd.DataFrame:
    """Query Prometheus range API and return a DataFrame with 'time' and 'value' columns."""
    resp = requests.get(
        f"{prom_url}/api/v1/query_range",
        params={"query": promql, "start": start, "end": end, "step": STEP},
        timeout=30,
    )
    resp.raise_for_status()
    data = resp.json()

    if data["status"] != "success":
        raise RuntimeError(f"Prometheus query failed: {data}")

    results = data["data"]["result"]
    if not results:
        return pd.DataFrame(columns=["time", "value"])

    # Take the first result vector (queries are aggregated sums)
    values = results[0]["values"]  # [[timestamp, "value"], …]
    df = pd.DataFrame(values, columns=["time", "value"])
    df["time"] = df["time"].astype(float)
    df["value"] = df["value"].astype(float)
    return df


def load_timestamps(csv_path: str) -> pd.DataFrame:
    """Load the timestamps CSV produced by run_all_tests.sh."""
    df = pd.read_csv(csv_path)
    df.columns = df.columns.str.strip()
    for col in ("start_time", "end_time"):
        df[col] = df[col].astype(int)
    df["iteration"] = df["iteration"].astype(int)
    return df


def align_and_resample(series_list: list[pd.DataFrame], freq_seconds: float = 5.0):
    """
    Align multiple DataFrames (columns: time, value) to a common
    normalised time axis (0-based seconds) and resample onto a uniform grid.
    Returns (time_axis, values_2d) where values_2d shape = (n_iterations, n_points).
    """
    resampled = []
    max_duration = max((df["time"].max() - df["time"].min()) for df in series_list if len(df))

    # Build uniform grid up to the longest run
    grid = np.arange(0, max_duration + freq_seconds, freq_seconds)

    for df in series_list:
        if df.empty:
            resampled.append(np.full_like(grid, np.nan))
            continue
        t0 = df["time"].iloc[0]
        rel = df["time"].values - t0
        vals = df["value"].values
        interp = np.interp(grid, rel, vals, left=np.nan, right=np.nan)
        resampled.append(interp)

    return grid, np.array(resampled)


# ── Main ────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Plot Prometheus metrics across test iterations.")
    parser.add_argument("stack_name", help="Stack name (must match the name passed to run_all_tests.sh)")
    parser.add_argument("--prometheus", default="http://localhost:30090", help="Prometheus base URL")
    args = parser.parse_args()

    results_dir = os.path.join(os.path.dirname(__file__), "results")
    csv_path = os.path.join(results_dir, f"{args.stack_name}_timestamps.csv")

    if not os.path.isfile(csv_path):
        print(f"ERROR: Timestamps file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    ts = load_timestamps(csv_path)
    test_ids = sorted(ts["test_name"].unique())

    print(f"Stack: {args.stack_name}")
    print(f"Tests found: {test_ids}")
    print(f"Prometheus: {args.prometheus}")
    print()

    # ── For every test, for every metric, gather iterations ─────────────
    for test_id in test_ids:
        test_rows = ts[ts["test_name"] == test_id].sort_values("iteration")
        n_iter = len(test_rows)
        print(f"  {test_id}: {n_iter} iteration(s)")

        fig, axes = plt.subplots(2, 2, figsize=(16, 10), sharex=False)
        fig.suptitle(
            f"{args.stack_name.upper()} – {test_id.upper()}  ({n_iter} iterations, mean ± σ)",
            fontsize=15,
            fontweight="bold",
        )

        for ax, (title, (promql, ylabel)) in zip(axes.flat, QUERIES.items()):
            iter_frames: list[pd.DataFrame] = []
            for _, row in test_rows.iterrows():
                try:
                    df = query_prometheus(args.prometheus, promql, row["start_time"], row["end_time"])
                    iter_frames.append(df)
                except Exception as exc:
                    print(f"    WARN: {title} iter {row['iteration']}: {exc}")
                    iter_frames.append(pd.DataFrame(columns=["time", "value"]))

            # Skip metric if no data at all
            non_empty = [f for f in iter_frames if not f.empty]
            if not non_empty:
                ax.set_title(f"{title}\n(no data)")
                continue

            time_axis, values_2d = align_and_resample(iter_frames)
            mean = np.nanmean(values_2d, axis=0)
            std = np.nanstd(values_2d, axis=0)

            # Convert time axis to minutes for readability
            t_min = time_axis / 60.0

            # Convert RAM bytes → MiB for RAM panels
            if "RAM" in title:
                mean = mean / (1024 ** 2)
                std = std / (1024 ** 2)
                ylabel = "RAM (MiB)"

            ax.plot(t_min, mean, linewidth=2, label="mean")
            ax.fill_between(t_min, mean - std, mean + std, alpha=0.25, label="± 1 σ")
            ax.set_ylabel(ylabel)
            ax.set_xlabel("Time (min)")
            ax.set_title(title)
            ax.legend(loc="upper right", fontsize=9)
            ax.grid(True, linestyle="--", alpha=0.5)
            ax.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))

        plt.tight_layout()
        out_path = os.path.join(results_dir, f"{args.stack_name}_{test_id}_dashboard.png")
        plt.savefig(out_path, dpi=200, bbox_inches="tight")
        plt.close(fig)
        print(f"    → saved: {out_path}")

    print("\nDone. All plots saved to results/.")


if __name__ == "__main__":
    main()
