#!/usr/bin/env python3
"""
plot_metrics.py – Offline Prometheus metric visualisation
=========================================================
Reads directly from the raw_data_<stack>.csv file generated by dump_prometheus_data.py.
Computes mean ± std across iterations, and plots error-band charts.

Usage:
    python3 plot_metrics.py <stack_name>
"""

import argparse
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

# Metric mapping (CSV metric_name -> Plot Title & Y-label)
METRIC_MAPPING = {
    "CPU_App": ("CPU – Application (default)", "CPU (cores)"),
    "CPU_Obs": ("CPU – Observability agents", "CPU (cores)"),
    "RAM_App": ("RAM – Application (default)", "RAM (MiB)"),
    "RAM_Obs": ("RAM – Observability agents", "RAM (MiB)"),
}

def align_and_resample(series_list: list[pd.DataFrame], freq_seconds: float = 5.0):
    """
    Align multiple DataFrames to a common 0-based time axis and resample.
    """
    if not series_list:
        return np.array([]), np.array([])
        
    max_duration = max(df["time_relative"].max() for df in series_list if not df.empty)
    if pd.isna(max_duration):
        return np.array([]), np.array([])

    grid = np.arange(0, max_duration + freq_seconds, freq_seconds)
    resampled = []

    for df in series_list:
        if df.empty:
            resampled.append(np.full_like(grid, np.nan))
            continue
        interp = np.interp(grid, df["time_relative"].values, df["value"].values, left=np.nan, right=np.nan)
        resampled.append(interp)

    return grid, np.array(resampled)

def main():
    parser = argparse.ArgumentParser(description="Plot metrics from raw CSV data.")
    parser.add_argument("stack_name", help="Stack name (e.g., stack_0)")
    args = parser.parse_args()

    results_dir = os.path.join(os.path.dirname(__file__), "results")
    csv_path = os.path.join(results_dir, f"raw_data_{args.stack_name}.csv")

    if not os.path.isfile(csv_path):
        print(f"ERROR: Raw data file not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    print(f"Loading offline data from {csv_path}...")
    df = pd.read_csv(csv_path)

    test_ids = sorted(df["test_name"].unique())
    print(f"Tests found in CSV: {test_ids}\n")

    for test_id in test_ids:
        test_df = df[df["test_name"] == test_id]
        iterations = sorted(test_df["iteration"].unique())
        n_iter = len(iterations)

        fig, axes = plt.subplots(2, 2, figsize=(16, 10), sharex=False)
        fig.suptitle(
            f"{args.stack_name.upper()} – {test_id.upper()}  ({n_iter} iterations, mean ± σ)",
            fontsize=15,
            fontweight="bold",
        )

        for ax, (csv_metric, (title, ylabel)) in zip(axes.flat, METRIC_MAPPING.items()):
            metric_df = test_df[test_df["metric_name"] == csv_metric]

            iter_frames = []
            for it in iterations:
                it_df = metric_df[metric_df["iteration"] == it].sort_values("time_relative")
                if not it_df.empty:
                    iter_frames.append(it_df)

            if not iter_frames:
                ax.set_title(f"{title}\n(no data)")
                continue

            time_axis, values_2d = align_and_resample(iter_frames)
            if len(time_axis) == 0:
                ax.set_title(f"{title}\n(no data)")
                continue

            mean = np.nanmean(values_2d, axis=0)
            std = np.nanstd(values_2d, axis=0)

            t_min = time_axis / 60.0

            # Convert RAM bytes to MiB
            if "RAM" in csv_metric:
                mean = mean / (1024 ** 2)
                std = std / (1024 ** 2)

            ax.plot(t_min, mean, linewidth=2, label="mean")
            # Only draw standard deviation band if we have more than 1 iteration
            if n_iter > 1:
                ax.fill_between(t_min, mean - std, mean + std, alpha=0.25, label="± 1 σ")
                
            ax.set_ylabel(ylabel)
            ax.set_xlabel("Time (min)")
            ax.set_title(title)
            ax.legend(loc="upper right", fontsize=9)
            ax.grid(True, linestyle="--", alpha=0.5)
            ax.xaxis.set_major_locator(ticker.MaxNLocator(integer=True))

        plt.tight_layout()
        out_path = os.path.join(results_dir, f"{args.stack_name}_{test_id}_dashboard.png")
        plt.savefig(out_path, dpi=200, bbox_inches="tight")
        plt.close(fig)
        print(f"    → saved: {out_path}")

    print("\nDone. All plots generated from CSV!")

if __name__ == "__main__":
    main()
