- name: Deploy stack 2 - Cilium eBPF + DaemonSet Observability (no sidecars)
  hosts: k3s_cluster
  gather_facts: true
  vars:
    stack_state: present
  vars_files:
    - ../secret
  roles:
    - cilium
    - prometheus_stack
    - loki
    - fluent_bit
    - otel_operator
    - otel_stack
    - jaeger_v2
    - google_demo
