- name: Deploy stack 4 - Full eBPF Stack 
  hosts: k3s_cluster
  gather_facts: true
  vars:
    stack_state: present
  vars_files:
    - ../secret
  roles:
    - cilium
    - prometheus_stack
    - loki
    - vector
    - jaeger_v2
    - google_demo
    - grafana_beyla

