[k3s_cluster]
primary_node ansible_host=PrimaryVM api_endpoint=PrimaryVM

[load_generator]
secondary_node ansible_host=SecondaryVM

[all:vars]
ansible_python_interpreter=/usr/bin/python3
api_port=6443
